<a href="https://colab.research.google.com/github/BhoomikaSheth/PythonBasicNotes/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)
print(np.info(np.add))

1.21.6
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
  

In [2]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [3]:
np.all(np.array([1,2,3,4]))

True

In [4]:
np.all(np.array([0,1,2,3,4]))

False

In [5]:
np.isfinite(np.array([1, 0, np.nan, np.inf]))

array([ True,  True, False, False])

In [6]:
np.isinf(np.array([1, 0, np.nan, np.inf]))

array([False, False, False,  True])

In [7]:
np.isnan(np.array([1, 0, np.nan, np.inf]))

array([False, False,  True, False])

In [8]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [9]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [10]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


In [11]:
#Write a NumPy program to create a 2D array of 10 zeros,10 ones, 10 fives.
a=np.array([np.zeros(10),np.ones(10),np.ones(10)*5])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [12]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 1.10062634 -1.90094317 -0.55910471 -0.58677306 -1.30451652  0.75705227
  0.72651262 -0.06868607 -0.72639098  0.81598651 -0.78356746 -1.51169995
 -0.74034474  0.09745182 -1.11039561]


In [13]:
#Write a NumPy program to multiply the values ​​of two given vectors.
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]
Vector-2
[9 4 7 1]
Multiply the values of two said vectors:
[ 9 32 21  5]


In [14]:
#Write a NumPy program to create a 3x4 matrix filled with values ​​from 10 to 21.
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [15]:
#Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [17]:
#Write a NumPy program to save a given array to a text file and load it.
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [18]:
#Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [19]:
#Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.

#Create the array using numpy.arange which returns evenly spaced values within a given interval.

nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [20]:
#Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html
print("Generate a uniform random sample with replacement:") 
print(np.random.choice(7, 5))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))  

Generate a uniform random sample with replacement:
[3 6 2 3 1]

Generate a uniform random sample without replacement:
[5 2 3 1 4]

Generate a non-uniform random sample with replacement:
[4 3 3 4 3]

Generate a uniform random sample without replacement:
[1 0 3 4 6]


In [21]:
np.random.random((5,5))

array([[0.40728984, 0.32300186, 0.6502229 , 0.88294753, 0.84193247],
       [0.14985089, 0.9059926 , 0.84719095, 0.99529083, 0.61616029],
       [0.95567155, 0.67345743, 0.78920283, 0.08339758, 0.92509746],
       [0.81488655, 0.14502934, 0.06376565, 0.33277718, 0.4989109 ],
       [0.31989792, 0.20188575, 0.62700056, 0.77797053, 0.24565802]])

In [22]:
np.empty((2,2))

array([[4.45e-323, 1.58e-322],
       [1.04e-322, 2.47e-323]])

In [23]:
import numpy as np # 3
a=np.array([1,2,3])
print(a)

a

[1 2 3]


array([1, 2, 3])

In [24]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
a.ndim,b.ndim  # num of dimensions

(1, 2)

In [26]:
a.shape,b.shape  # num of subdimensions

((3,), (2, 4))

In [27]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [28]:
a.dtype,b.dtype

(dtype('int64'), dtype('int64'))

In [29]:
a.itemsize,b.itemsize # memory size used by each data

(8, 8)

In [30]:
a.nbytes,b.nbytes #total memory used by array


(24, 64)

In [31]:
a.size,b.size # number of elements

(3, 8)

In [32]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:

b[1,2]=13

In [34]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6, 13,  8]])

In [35]:
b[1][2]


13

In [36]:
b[1,1:]

array([ 6, 13,  8])

In [37]:
b[1,1:]=15
b

array([[ 1,  2,  3,  4],
       [ 5, 15, 15, 15]])

In [38]:
a1=np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [39]:
a1=np.zeros(5,dtype=int)
a1

array([0, 0, 0, 0, 0])

In [40]:
a1=np.zeros(shape=(2,5),dtype=int)
a1


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
a2=np.ones(shape=(4,3,2),dtype=int)
a2

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [42]:
a3=np.arange(15,50,3).reshape(3,2,2 )
a3

array([[[15, 18],
        [21, 24]],

       [[27, 30],
        [33, 36]],

       [[39, 42],
        [45, 48]]])

In [43]:

a4=np.random.randint(15,50,size=(4,6))
a4

array([[37, 46, 15, 28, 37, 29],
       [42, 19, 21, 28, 31, 37],
       [48, 49, 18, 15, 20, 42],
       [48, 38, 38, 46, 18, 22]])

In [44]:
a5=np.random.rand(5,5)
a5


array([[0.02339998, 0.3122584 , 0.77094356, 0.27364829, 0.23659364],
       [0.31568432, 0.11469441, 0.59859429, 0.93995125, 0.11262801],
       [0.59599071, 0.05183556, 0.84583642, 0.57675747, 0.96329615],
       [0.14220255, 0.78586282, 0.44710046, 0.26323163, 0.50281329],
       [0.63301507, 0.90758272, 0.69993401, 0.21069384, 0.23342379]])

In [45]:
a6=np.identity(5)
a6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a=np.arange(1,17).reshape(4,4)
b=np.arange(110,126).reshape(4,4)
a+b

array([[111, 113, 115, 117],
       [119, 121, 123, 125],
       [127, 129, 131, 133],
       [135, 137, 139, 141]])

In [47]:
a*3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48]])

In [48]:
a**2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [49]:
#matrix multiplication
# rows x columns
np.matmul(a,b)

array([[1180, 1190, 1200, 1210],
       [3036, 3062, 3088, 3114],
       [4892, 4934, 4976, 5018],
       [6748, 6806, 6864, 6922]])

In [50]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [51]:
a7=np.ndarray(shape=(4,5),dtype=int)
a7

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024, 4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024, 4617315517961601024]])

In [52]:
a7=np.ndarray(shape=(4,5),dtype=float)
a7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [54]:
np.min(a),np.max(b),np.mean(a),np.median(a),np.sum(a)

(1, 125, 8.5, 8.5, 136)

In [55]:
np.mode(a)

AttributeError: ignored

Consider that you are a smartphone retailer and you have few smartphones in your inventory.

|Smartphone Model|Price (INR)|# Units Available|
|-|-|-|
|Samsung Galaxy M30S|	13999|	9|
Realme C2| 6298| 8|
Xiaomi Redmi Note 7 Pro| 10999| 9|
Xiaomi Redmi Note 8 Pro| 14999| 9|
Realme C2 32GB| 7298| 8|
Realme C2 2GB RAM| 6385| 8|
Realme 5| 8999| 9|
Xiaomi Redmi Note 7S 64GB| 9999| 6|
Xiaomi Redmi Note 8| 9999| 5|
Vivo Z1 Pro| 13868| 7|

Suppose you decided to do some analysis of your inventory. In the process, you want to find answers to the following questions:

1. What is the total monetary value of the inventory?

2. What is the average (or mean) price of a smartphone ?

3. What is the price of the cheapest smartphone in the inventory?

4. What is the price of the most expensive smartphone in the inventory?

5. What is the median price of a smartphone? 


In [92]:
import numpy as np

phones = np.array([[13999, 6298, 10999, 14999, 7298, 6385, 8999, 9999, 9999, 13868], [9,8,9,9,8,8,9,6,5,7]])
print(phones)

# r1c1*r2c1 + r1c2*r2c2 + .. 

print(np.sum(phones[0]*phones[1]))

print(np.min(phones[0]))

print(np.max(phones[0])) 

np.median(phones[0])

[[13999  6298 10999 14999  7298  6385  8999  9999  9999 13868]
 [    9     8     9     9     8     8     9     6     5     7]]
807877
6298
14999


9999.0

In [93]:
# Write a NumPy program to create a 2D array of 10 0s, 10 1s and 10 5s

import random 

yu = np.zeros(shape = (3,10), dtype = int)

yu[1] = np.ones(shape = (1,10), dtype = int)

yu[2] = np.random.randint(5,6,size=(1,10))

# yu

x = np.array([np.zeros(10, dtype = int), np.ones(10, dtype = int), np.ones(10, dtype = int)*5])

x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [94]:
# 3*4 Matrix Filled

y = np.arange(10,22).reshape(3,4)
y

t = np.zeros(shape = (10,10), dtype = int)
t[0] = 1
t[-1] = 1
t[:,0] = 1 
t[:,9] = 1

t

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [95]:
# Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

h = np.random.randint(10,15, size = (4,4))

print(h)

g = np.copy(h)

g[0] = h[3]
g[3] = h[0]

g

[[11 14 10 12]
 [14 13 10 13]
 [10 10 11 12]
 [12 12 11 10]]


array([[12, 12, 11, 10],
       [14, 13, 10, 13],
       [10, 10, 11, 12],
       [11, 14, 10, 12]])

In [96]:

# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

import numpy as np

dt = [("Name", "S15"), ("Height", int), ("Grade", int)]

st = [("John", 5, 3),("Son", 2, 2)]
stdata = np.array(st,dtype = dt)

np.sort(stdata, order = 'Height')

array([(b'Son', 2, 2), (b'John', 5, 3)],
      dtype=[('Name', 'S15'), ('Height', '<i8'), ('Grade', '<i8')])

In [97]:
a = np.array(["ABC", 4])

a.dtype

dtype('<U21')

In [98]:
# Write a NumPy program to sort an given array by the nth column.

v = np.random.randint(10, 100, size = (3,10))

print(v)

print(np.sort(v, axis = 1))

[[57 22 98 55 26 45 13 43 23 30]
 [58 71 79 96 76 83 77 21 70 18]
 [67 61 50 15 15 96 43 24 38 73]]
[[13 22 23 26 30 43 45 55 57 98]
 [18 21 58 70 71 76 77 79 83 96]
 [15 15 24 38 43 50 61 67 73 96]]


In [99]:
c = np.identity(3, dtype = int)

print(c)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [100]:
u = 1
for i in range(0, len(c)): # i = 0 1 2
  for j in range(0, len(c[i])):
    if c[i][j] == 1: 
      c[i][j] = u
      u += 1

c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [101]:
t = np.random.normal(160, 15, size = (5, 2000))
t

array([[146.05226212, 164.34505906, 155.23789594, ..., 170.90530843,
        145.85997958, 166.80568122],
       [152.73142468, 189.24392687, 154.14984326, ..., 160.1519162 ,
        185.75936902, 165.75186367],
       [169.39913637, 188.15864061, 181.8254527 , ..., 162.80399558,
        141.05209848, 120.90454217],
       [154.64900841, 141.50174174, 161.83657287, ..., 169.27139659,
        173.85883509, 163.87610365],
       [183.03293694, 180.4211486 , 150.54981495, ..., 174.27009027,
        148.64523672, 177.65743287]])

In [102]:
tt = np.all(np.array([1,2,3,4]))
tt

True

In [103]:
tt = np.all(np.array([1,2,0, 3,4]))
tt

False

In [104]:
yy = np.diag([1,2,3])
yy


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [105]:
np.nan

nan

In [106]:
np.inf

inf

In [107]:
np.isnan(np.array([1,0, np.nan, np.inf]))


array([False, False,  True, False])

In [108]:
np.isinf(np.array([1,0, np.nan, np.inf]))

array([False, False, False,  True])

In [109]:
np.isfinite(np.array([1,0, np.nan, np.inf]))

array([ True,  True, False, False])

In [110]:
np.iscomplex(np.array([1,0, 1+2j, np.inf]))

array([False, False,  True, False])

In [111]:

np.isreal(np.array([1,0, np.nan, np.inf]))

array([ True,  True,  True,  True])

In [112]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(np.greater(x,y))
print()
print(np.greater_equal(y,x))
print()
print(np.less(x,y))
print()
print(np.less_equal(x,y))
print()
print(np.equal(x,y))

[False False False False]

[ True  True  True  True]

[ True  True  True  True]

[ True  True  True  True]

[False False False False]


In [113]:
import numpy as np

q = np.arange(1,11)

print(q.dtype)

np.savetxt("Temp.txt", q, fmt = "%d")

e = np.loadtxt("Temp.txt")

int64


In [114]:
#. Replace all odd numbers in arr with -1 


#Stack arrays a and b vertically


# Get the common items between a and b


#Get the positions where elements of a and b match


#Get all items between 5 and 10 from an array


# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.


# Find the 5th and 95th percentile of an array


# drop rows containing missing values in a 2D numpy array


# Replace all ccurrences of nan with 0 in numpy array


# Find the unique values and the count of unique values in an array




In [115]:
import numpy as np
a=np.arange(1,11)
b=np.arange(1,11)**2
print(a)
print(b)
np.corrcoef(a,b)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]


array([[1.        , 0.97455863],
       [0.97455863, 1.        ]])

In [116]:
np.append(a,24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 24])

In [117]:
np.append(a,b)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,   4,   9,
        16,  25,  36,  49,  64,  81, 100])

In [118]:
np.insert(a,2,78)

array([ 1,  2, 78,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [120]:

np.where(a>2) # indices

(array([2, 3, 4, 5, 6, 7, 8, 9]),)

In [121]:
a[3]

4

In [122]:
a[[a>5]] # filtering values

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([ 6,  7,  8,  9, 10])

In [123]:
np.concatenate((a,b))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,   4,   9,
        16,  25,  36,  49,  64,  81, 100])

In [124]:
c=np.arange(1,13).reshape(3,4)
c

d=np.arange(20,32).reshape(3,4)
d

np.hstack((c,d))

array([[ 1,  2,  3,  4, 20, 21, 22, 23],
       [ 5,  6,  7,  8, 24, 25, 26, 27],
       [ 9, 10, 11, 12, 28, 29, 30, 31]])

In [125]:
np.vstack((c,d))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:

np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:

np.percentile(a,q=25)

3.25

In [128]:
import numpy as np
x = np.matrix('8 7; 3 -5')
print(type(x))
x

<class 'numpy.matrix'>


matrix([[ 8,  7],
        [ 3, -5]])

In [129]:
x = np.matrix([[8, 7], [3, -5]])
print(type(x))
x

<class 'numpy.matrix'>


matrix([[ 8,  7],
        [ 3, -5]])

In [130]:
x = np.matrix('8 7; 3 -5')
b = np.matrix('3; 2')
e = np.matmul(x, b)
e

matrix([[38],
        [-1]])

In [131]:
identity_matrix = np.identity(5, dtype = int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [132]:
some_matrix = np.matrix('1 2 3; 4 5 6; 7 8 9')
identity_matrix = np.identity(3, dtype = float)
mat_mult = np.matmul(some_matrix, identity_matrix)
mat_mult

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [133]:
mat_a = np.matrix('1 3 3; 1 4 3; 1 3 4')
inv_a = np.matrix('7 -3 -3; -1 1 0; -1 0 1')
np.matmul(mat_a, inv_a)

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [134]:
x = np.matrix('8 7; 3 -5')
det_x = np.linalg.det(x)
det_x

-60.99999999999995

In [135]:
mat_a = np.matrix('1 3 3; 1 4 3; 1 3 4')
det_a = np.linalg.det(mat_a)
det_a

1.0

In [136]:
mat_a = np.matrix('1 3 3; 1 4 3; 1 3 4')
inv_a = np.linalg.inv(mat_a)
inv_a

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [137]:
mat_x = np.matrix([[8, 7], [3, -5]])
mat_e = np.matrix('38; -1')
inv_x = np.linalg.inv(mat_x)
np.matmul(inv_x, mat_e)

matrix([[3.],
        [2.]])